#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Generate secret key.
python compose/production/django/secretkey.py

python manage.py migrate
{%- if cookiecutter.use_async == 'y' %}
uvicorn config.asgi:application --host 0.0.0.0 --reload
{%- else %}
python manage.py runserver_plus 0.0.0.0:8000
{%- endif %}
